### ISSUE TITLE
Can't use my old directory (NAS)

### ISSUE THREAD

**Issue by TheWux** [AndrewNeo/faextender-chrome#20] opened 2017-11-16 20:33 UTC
Hi, I'm not a real programmer so please be patient of my leak of knowlege.
I have the issue since the new FF Update that I can't go back to the old version or change the download directory to my NAS. I use it with a little Sync job to transfer my new stuff via Wifi to my phone or my tablet and now I have the problem that all new pictures go directly into the downloads directory and not in the old downloads directory to my NAS. 

Is there a workaround I could use?

~Wux

**Comment by AndrewNeo** [comment] 2017-11-17 08:45
You might be able to make a symlink inside your download directory, but there's nothing that can be done in the extension.

Duplicate of #11

**Closed by AndrewNeo** 2017-11-17 08:45 UTC
