### ISSUE TITLE
FA Extender largely non-functional in FireFox 57.0

### ISSUE THREAD

**Issue by DaMoot** [AndrewNeo/faextender-chrome#21] opened 2017-11-19 18:01 UTC
Recently got back from a business trip, PC updated, and now I cannot get FA Extender to work pretty much at all! 

It won't download. It won't open existing folders. It can tell if a file exists in an existing folder only about 8 times out of 10.

Have tried reinstalling FA Extender and FireFox both. Have tried older versions of FA Extender and nothing is working.

Can provide any logging you require for fix. Thanks!

Regards,
Nicholas

**Comment by AndrewNeo** [comment] 2017-11-21 07:45
This is due to changes by Mozilla as of 57.

Duplicate of #12

**Closed by AndrewNeo** 2017-11-21 07:45 UTC
