### ISSUE TITLE
Base functionality does not work at all in FF57+

### ISSUE THREAD

**Issue by nisbahmumtaz** [AndrewNeo/faextender-chrome#22] opened 2017-11-25 06:08 UTC
I'm sure you guys are all too aware of this. Just wanted to document the problems in the issues page.
Here are some issues that I'm facing:

- Not able to set or access custom directory (tried to copy paste my dir into the empty space within the addon... but will show [Error downloading]. The "default directory" is usually the default Microsoft Downloads folder. Sub-directories work fine.

- Images that are saved, then deleted in the "default directory", will no longer be downloadable through the addon (will persist as [File already exists.]).

**Comment by AndrewNeo** [comment] 2017-11-26 03:34
Duplicate of #12

**Closed by AndrewNeo** 2017-11-26 03:34 UTC
