### ISSUE TITLE
Save to Subdirectory resulting in "Error Downloading" Message on Firefox

### ISSUE THREAD

**Issue by Maneyframe** [AndrewNeo/faextender-chrome#17] opened 2017-10-03 09:45 UTC
As of the most recent update, when I download to a custom subdirectory ( E:\Art - Collected\_Furry ) I receive an [ERROR DOWNLOADING] Message. While on a custom subdirectory, the "Create Artist Subdirectories" field no longer stays checked either, after exiting the settings and going back into them. Everything functions perfectly when downloading to the default location of the downloads folder, including artist subdirectories

**Comment by Selth** [comment] 2017-10-03 16:24
I think FF is currently trying to force the 3.2.0 version as an update even though it's marked as non compatible with FF 55 and 56 and then because 3.2.1 is marked as uncompatible users won't get updated to 3.2.1.

**Comment by AndrewNeo** [comment] 2017-10-04 08:44
This is a duplicate of #11 , WebExtensions don't support downloading outside the download directory.

**Closed by AndrewNeo** 2017-10-04 08:44 UTC

**Comment by AndrewNeo** [comment] 2017-10-04 08:46
@Selth 3.2.1 doesn't fix the download path issue, it just clarifies it has to be a subdirectory. We can't downgrade older browsers though so users will have to do it manually.
